### ISSUE TITLE
Unable to recover when backend drops

### ISSUE THREAD

**Issue by mkmer** [shoejosh/aladdin-connect#10]
On thing I noticed recently with the new backend, is a failure of the add-on to reconnect after a connection error.  
If the backend goes off-line, the logs indicate an incorrect password and completely stops trying to connect.  There probably needs to be improved error detection with feedback to the calling software indicating the type of failure (No response from host, invalid password/user, invalid url, etc) allowing for a "smarter" decision on retrying.  Currently, the only path to recovery in home assistant is to reboot HA and hope the backend is alive.  

Probably more of an enhancement than a "bug".

**Comment by mkmer** [comment]
I've been researching this a bit further as I was updating the Home Assistant integration to include a configuration flow.  Hope to have the PR accepted by the next release. 
In your research of the API, did you find a websocket end point or other type of event based reply we could use rather than polling? I think we could really speed up the detection of the events for triggering automations.

**Comment by shoejosh** [comment]
@mkmer I had started on a HA PR for configuration flow as well but I just haven't had enough free time to finish it lately. I did plan on updating this library to add specific exception for various failure types as you've mentioned as part of that. I will get to it eventually, but I'll definitely make time to review/merge any PRs you or anyone else wants to make if you don't want to wait for me.

Also I have no idea about a websocket endpoint, I believe it was @twotimesthree that reverse engineered the new API.

**Comment by mkmer** [comment]
@shoejosh I have the config flow all finished and reviewed by a couple for
people,but it appears that I need someone to run the workflow because I'm a
first time contributor.
Maybe you can take a peak at the PR on HA and run the rest of the
workflow?  Either way, it could use a look from the "godfather" :-)

https://github.com/home-assistant/core/pull/68304#issue-1172495050

**Comment by mkmer** [comment]
@twotimesthree - anything to share on the API - something of the ASYNC opportunity?
