### ISSUE TITLE
Question on GET, POST format.  Not a problem with the code itself.

### ISSUE THREAD

**Issue by kimeckert** [shoejosh/aladdin-connect#2]
I am trying to implement these functions in JavaScript.  I am not a Python expert and cannot follow the code.  Do you have simple examples of the GET and POST commands that are sent to the server?

**Comment by shoejosh** [comment]
The API is pretty convoluted. I created some documentation for it using Postman. Hope this helps.

https://documenter.getpostman.com/view/5856894/RzZAjHxV

**Comment by apexad** [comment]
Not a fan of python either.  I have converted this to nodeJS/javascript
https://github.com/apexad/node-aladdin-connect-garage-door
