### ISSUE TITLE
[Question] Information

### ISSUE THREAD

**Issue by joshuaferr1s** [shoejosh/aladdin-connect#3]
Hi not sure if you even remember you wrote this code but I have been working on javascript version for controlling my garage door and I wondering how you found the endpoints?

**Comment by shoejosh** [comment]
I decompiled the Aladdin android app and also used [mitmproxy](https://mitmproxy.org/) to inspect requests/responses from the app.

Also, in case you weren't aware, someone has made a js library for this which might be helpful to you. https://github.com/apexad/node-aladdin-connect-garage-door

**Comment by joshuaferr1s** [comment]
Thanks for that! I finished my V1 of a OOP version [here](https://www.npmjs.com/package/genie-aladdin-connect)
