### ISSUE TITLE
No longer working?

### ISSUE THREAD

**Issue by mkmer** [shoejosh/aladdin-connect#5]
Recently something has changed with the infrastructure (around November 2021)? When connecting to the API it now always reports the door closed, no longer accepts open/close commands, shows the door "connected and online", and appears to throw the garage door offline from the phone app perspective.  When ever I issue commands via this tool the phone app immediately shows the opener offline... requires rebooting the door OR resetting the wifi connection to get it back.

Thoughts? How can I assist?

**Comment by bkuhns** [comment]
Just commenting to note that I'm also experiencing this ever since I updated to 2021.12.3 a few days ago. I think I was using an October build prior.

**Comment by mkmer** [comment]
New details:  Called OHD (Aladdin Connect) today. They have migrated their systems to a new server - something goes wrong with the migration putting (my and many other) opener in limbo - where the app shows it connected for a minute or so then disconnected.  
Not sure if the API has changed, but I will report back after they fix my "1/2 migration" to "full migration" and everything is working again.

**Comment by shoejosh** [comment]
@mkmer Did you ever get this resolved? My device is still working which leads to believe this is only affecting some users due to the bad migration on the Aladdin Connect side.

**Comment by mkmer** [comment]
@shoejosh They finally fully completed the migration, my apps now work, but the aladdin-connect shows 0 doors registered (where before they had a door that was always closed).  I did some de compiling of the phone app and running in the emulator. I see the app is connecting to a different site (AWS) and appears to authenticate with OAUTH.  I'm not super familiar with reverse engineering the solution, but my phone app is definitely connecting to a different backend - https://pxdqkls7aj.execute-api.us-east-1.amazonaws.com/ (NOT https://genie.exosite.com/api/portals/v1). 
Not sure if I can help in any way but am willing to share logs, test, etc.

**Comment by twotimesthree** [comment]
Below are the endpoints for their new API. You'll make an initial POST request to get a token (no more Basic Auth) and the token will be used in the header of subsequent calls. The token expires in 24hr, but I'm not sure if that's relevant for your library (just to the software that uses it). The email address needs to be URL encoded and the password is base64 encoded prior to URL encoding.

There is a hard-coded `X-Api-Key` header that you must use to access the service (this is not my personal key).  The app version is referenced both in the headers and within the body of the Authentication payload (which also includes the build number, visible in the nav menu of the app). It would be good to store these as variables so they can be periodically updated.

# Authentication
```
POST https://pxdqkls7aj.execute-api.us-east-1.amazonaws.com/Android/oauth/token
Content-Type: application/x-www-form-urlencoded
App_version: 5.25
X-Api-Key: fkowarQ0dX9Gj1cbB9Xkx1yXZkd6bzVn5x24sECW
User-Agent: okhttp/3.12.1

grant_type=password&client_id=1000&brand=ALADDIN&username=test%40example.com&password=dGVzdA%3D%3D&platform=platform&model=Google%20Pixel%206&app_version=5.25&build_number=2038&os_version=12.0.0
```
# Getting Door Names, IDs, and Current/Desired Status
JSON payload schema:
    devices[0].id  (integer) -- used as {deviceNum} below
    devices[0].doors[0].name   (string)
    devices[0].doors[0].status   (integer)
    devices[0].doors[0].door_index   (integer) -- used as {doorIndex} below
```
GET https://pxdqkls7aj.execute-api.us-east-1.amazonaws.com/Android/configuration
App_version: 5.25
Authorization: Bearer {FromTokenResponse}
X-Api-Key: fkowarQ0dX9Gj1cbB9Xkx1yXZkd6bzVn5x24sECW
User-Agent: okhttp/3.12.1
```
# Opening/Closing the door
There are two commands that can be used: `CloseDoor`, and `OpenDoor`
```
POST https://pxdqkls7aj.execute-api.us-east-1.amazonaws.com/Android/devices/{deviceNum}/door/{doorIndex}/command
Content-Type: application/json
App_version: 5.25
Authorization: Bearer {FromTokenResponse}
X-Api-Key: fkowarQ0dX9Gj1cbB9Xkx1yXZkd6bzVn5x24sECW
User-Agent: okhttp/3.12.1

{"command_key":"CloseDoor"}
```

@shoejosh

**Comment by pbelevich** [comment]
@twotimesthree thanks for the reverse engineering, I created a PR #6 which uses your instructions. It works with my garage door, but I'm still trying to figure out how to enable Aladdin Connect in home assistant

**Comment by shoejosh** [comment]
Thanks @twotimesthree and @pbelevich! I haven't had any spare time to work on this lately. I will go ahead and release a new version to pypi and then open a PR for home assistant. Will keep this open until then.

**Comment by shoejosh** [comment]
https://github.com/home-assistant/core/pull/65407
